from django.urls import path
from .views import (
    analyze_video, 
    register_user, 
    get_sessions, 
    get_session_details, 
    discard_session,
    get_profile, 
    update_profile, 
    create_goal, 
    get_goals,
    get_goal_details,
    update_goal, 
    cancel_goal,
    goal_progress,
    goal_completion,
    goal_trend,
    analysis_status,
    verify_otp,
    resend_otp,
    request_password_reset,
    reset_password_confirm,
    NotificationViewSet
)

urlpatterns = [
    path('analyze/', analyze_video),
    path('analysis_status/<int:session_id>/', analysis_status),
    path('register/', register_user, name='register'),
    path('verify-otp/', verify_otp),
    path('resend-otp/', resend_otp, name='resend_otp'),
    path('password-reset-request/', request_password_reset, name='password_reset_request'),
    path('password-reset-confirm/', reset_password_confirm, name='password_reset_confirm'),
    path('sessions/', get_sessions, name='sessions'),
    path('sessions/<int:session_id>/', get_session_details),
    path('sessions/<int:session_id>/discard/', discard_session),
    path('profile/', get_profile),
    path('profile/update/', update_profile),
    path('goals/create/', create_goal),
    path('goals/', get_goals, name='get_goals'),
    path('goals/<int:goal_id>/', get_goal_details),
    path('goals/<int:goal_id>/update/', update_goal),
    path('goals/<int:goal_id>/cancel/', cancel_goal),
    path('goals/<int:goal_id>/progress/', goal_progress),
    path('goals/<int:goal_id>/completion/', goal_completion),
    path('goals/<int:goal_id>/trend/', goal_trend),
    path('notifications/', NotificationViewSet.as_view({'get': 'list'}), name='notifications-list'),
    path('notifications/mark-all-read/', NotificationViewSet.as_view({'post': 'mark_all_as_read'}), name='notifications-mark-all'),
    path('notifications/<int:pk>/mark-read/', NotificationViewSet.as_view({'post': 'mark_as_read'}), name='notification-mark-one'),
]