# Generated by Django 5.2.9 on 2026-04-24 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GaitSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField(auto_now_add=True)),
                ('video_path', models.FileField(upload_to='uploads/')),
                ('thumbnail_path', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gait_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GaitAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('total_frames', models.IntegerField()),
                ('landmark_frames', models.IntegerField()),
                ('processing_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Completed', max_length=20)),
                ('processing_time_sec', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='analyzer.gaitsession')),
            ],
        ),
        migrations.CreateModel(
            name='KinematicMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_avg_angle', models.FloatField()),
                ('right_avg_angle', models.FloatField()),
                ('left_rom', models.FloatField()),
                ('right_rom', models.FloatField()),
                ('avg_rom', models.FloatField()),
                ('knee_symmetry_diff', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kinematic_metrics', to='analyzer.gaitanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='SpatialMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_step_length_norm', models.FloatField()),
                ('max_step_length_norm', models.FloatField()),
                ('step_length_symmetry', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spatial_metrics', to='analyzer.gaitanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='TemporalMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadence_bpm', models.FloatField()),
                ('avg_stride_time', models.FloatField()),
                ('stride_time_variability_std', models.FloatField()),
                ('stride_time_cv', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temporal_metrics', to='analyzer.gaitanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='UserGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(choices=[('avg_rom', 'Knee ROM'), ('knee_symmetry_diff', 'Knee Symmetry'), ('avg_step_length_norm', 'Step Length'), ('cadence_bpm', 'Cadence'), ('stride_time_cv', 'Stride Variability')], max_length=50)),
                ('target_value', models.FloatField()),
                ('current_value_at_start', models.FloatField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Achieved', 'Achieved'), ('Cancelled', 'Cancelled')], default='Active', max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('height_cm', models.FloatField()),
                ('weight_kg', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
