# Generated by Django 5.2.9 on 2026-04-24 21:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_alter_userprofile_age_alter_userprofile_gender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usergoal',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Active')), fields=('user', 'metric_name'), name='unique_active_goal_per_metric'),
        ),
    ]
