# Generated by Django 5.2.9 on 2026-04-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_usergoal_unique_active_goal_per_metric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaitanalysis',
            name='landmark_frames',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gaitanalysis',
            name='processing_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Detecting Pose', 'Detecting Pose'), ('Extracting Features', 'Extracting Features'), ('Completed', 'Completed'), ('Failed - No landmarks detected', 'Failed - No landmarks detected')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='gaitanalysis',
            name='processing_time_sec',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='gaitanalysis',
            name='total_frames',
            field=models.IntegerField(default=0),
        ),
    ]
