# Generated by Django 5.2.9 on 2026-04-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_alter_gaitanalysis_landmark_frames_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaitanalysis',
            name='processing_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Detecting Pose', 'Detecting Pose'), ('Extracting Features', 'Extracting Features'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Failed - No landmarks detected', 'Failed - No landmarks detected')], default='Pending', max_length=50),
        ),
    ]
