# Generated by Django 5.2.9 on 2026-05-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0006_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='last_sent',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
