# Generated by Django 5.2.9 on 2026-05-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0008_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergoal',
            name='achieved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usergoal',
            name='achieved_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
