# Generated by Django 5.2.9 on 2026-05-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0010_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergoal',
            name='final_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
