# Generated by Django 5.2.9 on 2026-06-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0011_usergoal_final_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaitsession',
            name='processed_video_path',
            field=models.FileField(blank=True, null=True, upload_to='processed_videos/'),
        ),
        migrations.AddField(
            model_name='gaitsession',
            name='skeleton_video_path',
            field=models.FileField(blank=True, null=True, upload_to='processed/'),
        ),
    ]
