# Generated by Django 5.2.9 on 2026-06-01 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0012_gaitsession_processed_video_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gaitsession',
            name='processed_video_path',
        ),
    ]
