# Generated by Django 5.2.9 on 2026-06-04 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0013_remove_gaitsession_processed_video_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergoal',
            name='achieved_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achieved_goals', to='analyzer.gaitsession'),
        ),
        migrations.AddField(
            model_name='usergoal',
            name='invalid_reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
