# Generated by Django 5.2.9 on 2026-06-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0014_usergoal_achieved_session_usergoal_invalid_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaitanalysis',
            name='ai_interpretation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
