# Generated by Django 5.2.9 on 2026-06-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0015_gaitanalysis_ai_interpretation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('bio', models.TextField()),
                ('experience_years', models.IntegerField(default=1)),
                ('profile_picture_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
